### ISSUE TITLE
Full list of implemented and possible operators

### ISSUE THREAD

**Issue by Magnogen** [TodePond/MotherTode#16]
## List of operators
It seemed as though the list was going quite quickly, so I've compiled them here.

- ✔ Many `Term+`
  Matches 1 or more occurences of a term

- ✔ Any `Term*` `{ Terms }`
  Matches 0 or more occurences of a term ( perhaps this could just be replaced with `Term+?` or `Term?+` ? )

- ✔ Maybe `Term?` `[ Terms ]`
  Matches 0 or 1 occurences of a term

- ✔ Or `Term1 | Term2` `< Terms >`
  Matches any of the terms in the 'list' of options

- ✔ Except `Term1~Term2`
  Matches a term, but only if its not a part of another term

- ❌ Select `@Term`
  Labels a term for later use, serves no functional purpose

- ❌ Then `Term THEN Term` `Term, Term`
  Matches multiple terms in sequence

- ❌ Count `N Term` ( perhaps can be simplified to `NTerm`, if you restrict terms to only be defined with alphabetic characters)
  Matches a specific number (N) of terms in sequence

### The following are suggestions for possible operators

- ❔ But / Not `#Term` `NOT Term` ( `{ Terms }` if you end up removing the Any term, as mentioned above )
  Matches anything that is not a Term

- ❔ Anything `...` `ANY`
  Any term. After thinking about this, it'd probably be a bad idea to use this in conjunction with Many or Any, unless it becomes lazy like in regex

- ❔ Built-ins `:name:` ( inspired by Character Classes in the regex POSIX standard [Source](https://www.gnu.org/software/gcal/manual/html_node/Regexp-Operators.html) )
  This is more like a group of built in terms, but I thought I could put it in here anyway
  Types of characters which turn up it lots of places, so its helpful to have a group that can be used from the beginning, including:
  - `:alnum:`
    Alphanumeric characters
  - `:punct:`
    Punctuation characters 
  - `:xdigit:`
    Characters that are hexadecimal digits

**Comment by Magnogen** [comment]
I'd be happy to tick off the operators when they are completed by updating my comment

**Comment by TodePond** [comment]
It's helpful to see it all laid out like this!

I have the 'any' operator as its own thing because it's from 'EBNF'. This makes me realise that MotherTode's 'or' operator works differently to EBNF. Maybe it would make more sense if it worked the same way...

And maybe built-ins! That would be a nice way of differentiating then. I wonder what built-ins would be helpful. I guess `EOF` could be a built-in too.

**Comment by Magnogen** [comment]
Yeah! The EOF operator would make sense as an in-built term, and if your going with that, you could also implement a SOF (Start Of File) term too.

EBNF separates it's terms with commas, and you've decided against that, so in a similar sense you could leave the ORperator (bah dum tss) as it is. But it is your language, so you can do what you you think would work best.

**Comment by TodePond** [comment]
That's true! I wonder if commas could be optional actually! Start of file makes sense too. I think close to EBNF would be good, with a few liberties. Arbitrary things like the or operator, I see no reason not to be the same as EBNF

**Comment by Magnogen** [comment]
Hmm, yeah I can undesrtand you reasoning. Go for it! After all, the more similarities it has to other languages, the easier it'll be for people to learn!

**Comment by TodePond** [comment]
Closing because of upcoming rewrite
