### ISSUE TITLE
Documentation doesn't emphasise significant indentation

### ISSUE THREAD

**Issue by TodePond** [TodePond/MotherTode#4]
The docs could be clearer on this. And they could specify that only tabs are currently supported. And that double indentation is currently not supported.

**Comment by Magnogen** [comment]
Would it be possible to use a custom tab string? Maybe in an options object?

Something like
```
const language = MotherTode(` ... `, {
    tab_character: "  ",
    // and maybe anything else you may want to include in future?
});
```

**Comment by TodePond** [comment]
Yes that could be possible as a short-term fix! In my other language, SpaceTode, it automatically detects what indentation you are using (tabs/2spaces/4spaces/2tabs/99spaces/etc) so I hope to change MotherTode to that system once the syntax has settled down a bit.

**Comment by Magnogen** [comment]
Sounds like a pretty good idea, looking forward to seeing how this turns out!

**Comment by TodePond** [comment]
I added a placeholder line about indentation for the time-being, until a better fix is applied. See #8 and #6

**Comment by TodePond** [comment]
Also #9

**Comment by Magnogen** [comment]
Haha, it appears as though indentation is a tough feature to implement!
